### ISSUE TITLE
Integration with loopback-component-storage

### ISSUE THREAD

**Issue by beeman** [mbouclas/loopback-component-image-uploads#2]
In my projects I'm working with [loopback-component-storage](https://github.com/strongloop/loopback-component-storage) to store the files to either the server or a remote storage like S3. 

It would be nice if this component has support for this. Can you tell me if it's on the roadmap?

**Comment by mbouclas** [comment]
I suppose it can be done, but it would have to be a two -three step process. An image needs to be uploaded via the storage component to the loopback server, then it would have to be resized and then transferred to the remote storage. 

I will have a crack at it when i get some time cause i would have to check the storage component's source in order to find the optimal solution
